name: deploy suma site to github pages

on:
  # runs on pushes to the master branch
  push:
    branches: ["master"]

  # allows you to run this workflow manually from the actions tab
  workflow_dispatch:

# sets permissions of the GITHUB_TOKEN to allow deployment to github pages
permissions:
  contents: read
  pages: write
  id-token: write

# allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # build job
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout your repository
      - name: checkout
        uses: actions/checkout@v4

      # setup bun environment
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      # install dependencies
      - name: install dependencies
        run: bun install

      # build the vite site
      - name: build with vite
        run: bun run build

      # copy index.html to 404.html to handle 404 on github pages
      - name: copy index to 404
        run: cp ./dist/index.html ./dist/404.html

      # upload the build artifact
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
